version: "2"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/bin/data/db
    ports:
      - "27019:27017"
    volumes:
      - ./southpark-api-db:/bin/db
    restart: always
    command: mongod

  web:
    image: southpark-api-node:latest
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongo

volumes:
  southpark-api-db: