version: "3.1"

services:
  db:
    image: mongo:4.0
    environment:
      - MONGO_DATA_DIR=/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - gig-buddy-data:/db/data/db
    restart: always
    command: mongod

  web:
    image: ccahill/gig-buddy-node:latest
    env_file: .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db

volumes:
  gig-buddy-data: